trigger:
  - test/pipeline-windows

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.18.3"
    displayName: "Install Node.js"

  - script: |
      echo "Installing Yarn globally..."
      npm i
    displayName: "Install Dependencies"

  - script: |
      echo "Running tests..."
      npm run test
    displayName: "Run tests with logging"
    continueOnError: true
    env:
      BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
  - script: |
      ls
    displayName: "show folder list"
  - script: |
      git remote -v
      git branch
      git config --global user.email "v-zhangtianc@microsoft.com"
      git config --global user.name "Yionse"
      git checkout -b test/pipeline-windows-new
      git add .
      git commit -m 'update'

      git push -u origin test/pipeline-windows-new
    displayName: "Configure Git and Push"
