trigger:
  - test/pipeline-windows

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.18.3"
    displayName: "Install Node.js"

  - script: |
      echo "Installing Yarn globally..."
      npm i
    displayName: "Install Dependencies"

  - script: |
      echo "echo"
      pwd
      ls
    displayName: "test"

  - script: |
      echo "Running tests..."
      npm run test || echo "Test command failed!"
    displayName: "Run tests with logging"
    continueOnError: true
  - script: |
      ls
    displayName: "show folder list"
  - script: |
      git config --global user.email "v-zhangtianc@microsoft.com"
      git config --global user.name "Yionse"

      # 确保切换到目标分支
      git checkout test/pipeline-windows

      # 拉取最新代码，避免冲突
      git pull origin test/pipeline-windows --rebase

      # 添加并提交更改
      git add .
      git commit -m 'update'

      # 再次确保是正确的分支
      git push origin test/pipeline-windows
    displayName: "Configure Git and Push"
